services:
  - type: web
    name: parada-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 7d
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://paradacebuv1.vercel.app
    healthCheckPath: /health
    autoDeploy: true 